services:
  craftstatusbot:
    build: .
    container_name: craftstatusbot
    env_file:
      - .env
    #volumes:
    #  - /data/logs/latest.log:/latest.log:ro # Onde o latest.log do seu servidor se encontra
    #  - /data/world/stats:/stats:ro # Onde a pasta stats do seu servidor se encontra
    #  - ./players.json:/app/bot/core/utils/json/players.json:ro
    # Only map it if SERVER_MODE=1